language: java
jdk:
- oraclejdk8
env:
  matrix:
    secure: oq+GndKtUUrHka8qe36vZN6+soxMZGHOWhZwN6bLSO5GtAZTVlmxtmdlJseUYZ46mcpMc/Wn42xlHyw/IxT2m9h2jHNqA+X89zARqTp/l97dk9fyg8YOgtIrDooSOeaN3eqOtbm8jY7VPLJmq1srTcTa97YvcUqxskeOiYWzMDQ85/ftMy/2OUbWl3ANjzTdK0Mb6ikLTOzboPq7lT7TuBS3Klqv4VaitO3euD73UQ68zYHKJFaIBbNI/XlmzH6QAb+tE/hoxL1Km3nc3OEBVLSxsx9ORNoG/JkMSh1a+Z8Fn1BPLhQjtkkRDhCTEif3H77unCqiJc0B6YBQjgAbcdM2bwPeO9mg8TL49SoFlkrtXtMWqTHEexYZndIZryMFGWCRuJnzf7pDdUkrVImDIWWd5P1vMpf+GKtjXNs8wMLHS8yD1HkkDT4TxQX5PbaKHJoTnGAUrLacM1c7vtisdg9Jfhs9b9aifqI1TNZSrr5AycvOTOEU2Ot33u6Wg+yHL9waHH0lbNL2YN4z7DTkb3gPALlMAfRHPmzym1hQSoFEar8LG0YdrlVKZ0brfRhBajvihccpoSJPIz/KY8CdtbWnel9f432FSR0q/7CuojCUgkUdDdjD1NZvtTxc9PyPZJQ6kh5k6u+HoW+VUE0p7Ar7hFn1Tz2KI8rLV3/srr8=
install: true
script: ./buildViaTravis.sh
